#+TITLE: A clean emacs config is an empty config file.
#+AUTHOR: Jakob Klemm
#+EMAIL: jakob.klemm@protonmail.com
#+OPTIONS: toc:nil num:nil
Emacs Config - Jakob Klemm
* Installation
** Fonts
	1. Download fonts with =M-x all-the-icons-install-fonts=
	2. Install the fonts
** Gcal
	 Setup or delete gcal, under Org/Agenda.
	 Gcal need google oauth credentials, instructions can be found under [[https:github.com/myuhe/org-gcal.el][org-gcal]]
	 Create a file called =secret.el= and insert the =org-cal= example config in
	 there. Set all the three variables in there.
** Binds
	All used keybinds
	 | Key                   | Executes                       |
	 |-----------------------+--------------------------------|
	 | C-f                   | move-right                     |
	 | C-b                   | move-left                      |
	 | C-n                   | move-down                      |
	 | C-p                   | move-up                        |
	 | C-a                   | line-begin                     |
	 | C-e                   | line-end                       |
	 | <TAB>                 | org-table, org-navigation      |
	 | <TAB>                 | yas-expand                     |
	 | C-<TAB>               | yas-expand                     |
	 | C-x g                 | magit-status                   |
	 | C-x p                 | magit-init                     |
	 | C-s                   | swipe                          |
	 | C-x C-f               | ido-file                       |
	 | C-x C-f C-f           | dired-file                     |
	 | C-c p                 | projectile-map                 |
	 | C-c p				 | projectile-command-map         |
	 | C-x o                 | other window                   |
	 | C-x j                 | close buffer & window          |
	 | C-x 3                 | right-open-window              |
	 | C-x 2                 | down-open-window               |
	 | C-x 4 f               | right-open-file                |
	 | C-x 4 b               | right-open-buffer              |
	 | C-x t                 | terminal-emulator              |
	 | C-x u                 | undo (& redo)                  |
	 | C-c t                 | org-todo                       |
	 | C-c a                 | org-agenda                     |
	 | C-c d                 | org-deadline                   |
	 | C-c g                 | gcal-post                      |
	 | C-c f                 | gcal-fetch                     |
	 | C-c x                 | todo-done                      |
	 | C-c q                 | org-tags                       |
	 | C-c v                 | org-agenda-add-file            |
	 | C-c d                 | google-this                    |
	 | C-c s                 | org-schedule                   |
	 | C-c n                 | deft-mode                      |
	 | C-<RETURN>            | (deft only) new note with name |
	 | C-c C-x C-s           | mark as done and archive       |
	 | C-c C-a               | org-attach                     |
	 | C-c C-j               | org-goto                       |
	 | C-c C-l               | org-insert-link                |
	 | C-c C-o               | org-open-at-point              |
	 | C-c C-q               | org-set-tags-command           |
	 | C-c C-r               | org-reveal                     |
	 | C-c C-s               | org-schedule                   |
	 | C-c C-t               | org-todo                       |
	 | C-c C-z               | org-add-note                   |
	 | C-c SPC               | org-table-blank-field          |
	 | C-c +		         | org-table-sum                  |
	 | C-c ,		         | org-priority                   |
	 | C-c .		         | org-time-stamp                 |
	 | C-c =		         | org-table-eval-formula         |
	 | C-c ?		         | org-table-field-info           |
	 | C-c ^		         | org-sort                       |
	 | C-.                   | ispell word                    |
	 | M-<LEFT>              | org-table-move-column-left     |
	 | M-S-<LEFT>            | org-table-delete-column        |
	 | M-S-<RIGHT>           | org-table-move-column-right    |
	 | M-S-<RIGHT>           | org-table-insert-column        |
	 | M-<UP>                | org-table-move-row-up          |
	 | M-<DOWN>              | org-table-move-row-down        |
	 | M-S-<UP>              | org-table-kill-row             |
** Dict
   (Windows)
   Set DICPATH variable to the correct dictionary. Use =ispell= with =C-.=
   Config comes with two dictionaries, English and German, found under =dict/=.
   dictionary

** Control
*** Open files
		Open files with a different program than emacs.
		1. =C-x C-f= (Ido Mode)
		2. =C-f= (Dired-mode)
		3. Fullscreen dired
		4. Select file
		5. Type =!= for the command line.
		6. Type =chrome= for PDF's, etc.
* Setup
** =use-package=
  Verify the =use-package= installation and ensures the packages.
  #+begin_src emacs-lisp
	(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

	(require 'use-package)
	(setq use-package-always-ensure t)
  #+end_src
** Update and compile
  Update and compile all packages.
  #+begin_src emacs-lisp
  (use-package auto-compile
    :config (auto-compile-on-load-mode))
  (setq load-prefer-newer t)
  #+end_src
** Defaults
  Default settings cloned from [[https://github.com/hrs/sensible-defaults.el][Harry R. Schwartz]].
  Functions:
  - Ensuring that files end with newlines,
  - Always enabling syntax highlighting,
  - Increasing the garbage collection threshold,
  - Defaulting line-length to 80 characters,
  - Creating parent directories after saving a deeply nested file.
  #+begin_src emacs-lisp
  (load-file "~/.emacs.d/sensible-defaults.el/sensible-defaults.el")
  (sensible-defaults/use-all-settings)
  (sensible-defaults/use-all-keybindings)
  ;; Disable all backups.
  (setq make-backup-files nil)
  #+end_src
** Resources
  Add =resources= to the path
  #+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/resources/")
  #+end_src
* Interface
** Scroll bar
   Disable the scroll bar in the entire window and mini buffers.
   #+begin_src emacs-lisp
   ;; Menu bar
   (tool-bar-mode 0)
   (menu-bar-mode 0)
   (scroll-bar-mode -1)
   ;; Minibuffer
   (set-window-scroll-bars (minibuffer-window) nil nil)
   #+end_src
** Improvements
*** Symbols
    Prettify symobls.
    #+begin_src emacs-lisp
    (global-prettify-symbols-mode 1)
    (defun add-pretty-lambda ()
    "Make some word or string show as pretty Unicode symbols.  See https://unicodelookup.com for more."
    (setq prettify-symbols-alist
    '(
    ("lambda" . 955)
    ("delta" . 120517)
    ("epsilon" . 120518)
    ("->" . 8594)
    ("<-" . 8592)
    ("<=" . 8804)
    (">=" . 8805)
    ("=~" . 8771)
    ("!=" . 8800)
    (":=" . 8788)
    )))
    (add-hook 'prog-mode-hook 'add-pretty-lambda)
    (add-hook 'org-mode-hook 'add-pretty-lambda)
    #+end_src
*** Mod line
	Doom mod line.
		#+begin_src emacs-lisp
		(use-package doom-modeline
		:ensure t
		:init (doom-modeline-mode 1))
        #+end_src
		Config and settings for mod line, from [[https:github.com/seagle0128/doom-modline][doom-modline]]
		#+begin_src emacs-lisp
		(setq doom-modeline-icon (display-graphic-p))
		(setq doom-modeline-major-mode-icon t)
		(setq doom-modeline-buffer-state-icon t)
		(setq doom-modeline-buffer-modification-icon t)
		(setq doom-modeline-unicode-fallback nil)
		(setq doom-modeline-minor-modes nil)
		(setq doom-modeline-enable-word-count nil)
		(setq doom-modeline-buffer-encoding t)
		(setq doom-modeline-lsp t)

		;; Whether display the environment version.
		(setq doom-modeline-env-version t)
		;; Or for individual languages
		(setq doom-modeline-env-enable-python t)
		(setq doom-modeline-env-enable-ruby t)
		(setq doom-modeline-env-enable-perl t)
		(setq doom-modeline-env-enable-go t)
		(setq doom-modeline-env-enable-elixir t)
		(setq doom-modeline-env-enable-rust t)
		(display-time-mode 1)
		#+end_src
*** Minor modes
   Hide all minor modes with =minions=.
   #+begin_src emacs-lisp
   (use-package minions
   :config
   (setq minions-mode-line-lighter ""
   minions-mode-line-delimiters '("" . ""))
   (minions-mode 1))
   #+end_src
*** Scrolling
   Don't skip to center of page when at bottom / top, /normal/ smooth scrolling.
   #+begin_src emacs-lisp
   (setq scroll-conservatively 100)
   #+end_src
*** Fullscreen
   #+begin_src emacs-lisp
   (add-to-list 'default-frame-alist '(fullscreen . maximized))
   #+end_src
*** Current line
    Hightlight the current line.
    #+begin_src emacs-lisp
    (global-hl-line-mode)
		;; Marked number
		(set-face-background hl-line-face "#090405")
    #+end_src
*** Line numbers
   #+begin_src emacs-lisp
    (global-display-line-numbers-mode)
   #+end_src
*** Kill and close
		Kill the current buffer and close the window in one command.
		#+begin_src emacs-lisp
		(global-set-key (kbd "C-x j") 'kill-buffer-and-window)
		#+end_src
*** Cursor
Set the cursor color to the same as beacon.
#+begin_src emacs-lisp
(set-cursor-color "#c678dd")
#+end_src
** Theme
Used themes:
- Elixify - AstonJ (elixirforum)
- Doom-nord
- Doom-material
- Doom-spacegrey
#+begin_src emacs-lisp
(use-package doom-themes)
;; (load-theme `doom-nord t)
;; (load-theme `doom-material t)
;; (load-theme `doom-spacegrey t)
(load-theme `doom-acario-dark)
#+end_src
** Dashboard
   Setup the dashboard with come modifications and configs.
*** Dependancies
   Page-break-lines
   #+begin_src emacs-lisp
   (use-package page-break-lines)
   (turn-on-page-break-lines-mode)
   #+end_src
   Install icons.
   (Not only used by =dashboard= but its the main dependancy.
   #+begin_src emacs-lisp
   (use-package all-the-icons)
   #+end_src
*** Setup
    Setup the dashboard.
    #+begin_src emacs-lisp
    (use-package dashboard)
    (dashboard-setup-startup-hook)
    ;; Or if you use use-package
    (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook))
    #+end_src
*** Config
    Options and configuration for dashboard following the readme.
    #+begin_src emacs-lisp
    ;; Set the banner
    (setq dashboard-startup-banner 2)
    ;; Content is not centered by default. To center, set
    (setq dashboard-center-content t)
    ;; Icons
    (setq dashboard-set-heading-icons t)
    (setq dashboard-set-file-icons t)
    ;; Navigator
    (setq dashboard-set-navigator t)
    ;; Init info
    (setq dashboard-set-init-info t)
    ;; Message
    (setq dashboard-footer-messages '("Every time I see this package I think to myself \"People exit Emacs?\""))
    #+end_src
** Font
	 Use Fira Code as default font.
	 #+begin_src emacs-lisp
	 (set-face-attribute
	 'default nil
	 :font "Fira Code"
	 :weight 'normal
	 :width 'normal
	 )
	 #+end_src
** New window
	 Directly switch to new window after opening.
	 (Credit: hrs)
	 #+begin_src emacs-lisp
	 (defun hrs/split-window-below-and-switch ()
   "Split the window horizontally, then switch to the new pane."
   (interactive)
   (split-window-below)
   (balance-windows)
   (other-window 1))

	 (defun hrs/split-window-right-and-switch ()
   "Split the window vertically, then switch to the new pane."
   (interactive)
   (split-window-right)
   (balance-windows)
   (other-window 1))

	 ;; Keys
	 (global-set-key (kbd "C-x 2") 'hrs/split-window-below-and-switch)
	 (global-set-key (kbd "C-x 3") 'hrs/split-window-right-and-switch)
	 #+end_src
** Beacon
	 Beacon for highlighting the cursor when switching buffers.
	 #+begin_src emacs-lisp
	 (use-package beacon
   :custom
   (beacon-color "#c678dd")
   :hook (after-init . beacon-mode))
	 #+end_src
** Title
	 Set the window title to the current file.
	 #+begin_src emacs-lisp
	 (setq-default frame-title-format
   '(:eval
   (format "%s@%s: %s %s"
   (or (file-remote-p default-directory 'user)
   user-real-login-name)
   (or (file-remote-p default-directory 'host)
   system-name)
   (buffer-name)
   (cond
   (buffer-file-truename
   (concat "(" buffer-file-truename ")"))
   (dired-directory
   (concat "{" dired-directory "}"))
   (t
   "[no file]")))))
	 #+end_src
* Projects
** General
*** Indentation
    Copied from [[https://github.com/MatthewZMD/.emacs.d][.emacs.d]]
		#+begin_src emacs-lisp
		(use-package highlight-indent-guides
		:if (display-graphic-p)
		:diminish
		;; Enable manually if needed, it a severe bug which potentially core-dumps Emacs
		;; https://github.com/DarthFennec/highlight-indent-guides/issues/76
		:commands (highlight-indent-guides-mode)
		:custom
		(highlight-indent-guides-method 'character)
		(highlight-indent-guides-responsive 'top)
		(highlight-indent-guides-delay 0)
		(highlight-indent-guides-auto-character-face-perc 7))
    	#+end_src
		Indent config
		#+begin_src emacs-lisp
		(setq-default indent-tabs-mode nil)
		(setq-default indent-line-function 'insert-tab)
		(setq-default tab-width 4)
		(setq-default c-basic-offset 4)
		(setq-default js-switch-indent-offset 4)
		(c-set-offset 'comment-intro 0)
		(c-set-offset 'innamespace 0)
		(c-set-offset 'case-label '+)
		(c-set-offset 'access-label 0)
		(c-set-offset (quote cpp-macro) 0 nil)
		(defun smart-electric-indent-mode ()
		"Disable 'electric-indent-mode in certain buffers and enable otherwise."
		(cond ((and (eq electric-indent-mode t)
        (member major-mode '(erc-mode text-mode)))
        (electric-indent-mode 0))
        ((eq electric-indent-mode nil) (electric-indent-mode 1))))
		(add-hook 'post-command-hook #'smart-electric-indent-mode)
        #+end_src
*** CamelCase
    Treat camel casing (the best and only right variable naming system) as multiple words.
    #+begin_src emacs-lisp
    (use-package subword
    :config (global-subword-mode 1))
    #+end_src
*** UTF-8
    Treat every file as UTF-8 by default.
    #+begin_src emacs-lisp
    (set-language-environment "UTF-8")
    #+end_src
*** Wrap
		Auto wrap paragraphs. Or use =M-q=.
    #+begin_src emacs-lisp
		(add-hook 'text-mode-hook 'auto-fill-mode)
		(add-hook 'gfm-mode-hook 'auto-fill-mode)
		(add-hook 'org-mode-hook 'auto-fill-mode)
    #+end_src
*** Spacing
		Cycle spacing options.
		#+begin_src emacs-lisp
		(global-set-key (kbd "M-SPC") 'cycle-spacing)
		#+end_src
*** Modes
		Other /cool/ default modes.
		#+begin_src emacs-lisp
		(show-paren-mode 1)
		(column-number-mode 1)
		(size-indication-mode 1)
		(transient-mark-mode 1)
		(delete-selection-mode 1)
    #+end_src
*** Kill current
		Kill the current buffer instead of asking.
		#+begin_src emacs-lisp
		(defun kill-current-buffer ()
    (interactive)
    (kill-buffer (current-buffer)))

		;; Keybind
		(global-set-key (kbd "C-x k") 'kill-current-buffer)
		#+end_src
*** Save
		Save the location within a file.
		#+begin_src emacs-lisp
		(save-place-mode t)
		#+end_src
*** Which key
		Helpful with long keybinds.
		#+begin_src emacs-lisp
		(use-package which-key
		:config (which-key-mode))
		#+end_src
*** Jump
		Jump to function definitions.
		(Works with elixir)
		#+begin_src emacs-lisp
		(use-package dumb-jump
		:ensure t
		:bind (("M-g o" . dumb-jump-go-other-window)
    ("M-g j" . dumb-jump-go))
		:config (setq dumb-jump-selector 'ivy))
	  #+end_src
*** google-this
		Automaticly google something.
		#+begin_src emacs-lisp
		(use-package google-this)
		(google-this-mode 1)
		(global-set-key (kbd "C-c d") 'google-this)
		#+end_src
*** Terminal
		Bind =C-x t= to =eshell=.
		#+begin_src emacs-lisp
		(global-set-key (kbd "C-x t") 'eshell)
		#+end_src
** Completion
   Use package =company= as a dependency of lsp-mode.
   #+begin_src emacs-lisp
   (use-package company)
   (add-hook 'after-init-hook 'global-company-mode)
   (use-package lsp-mode
   :commands lsp
   :ensure t
   :diminish lsp-mode
   :hook
   (elixir-mode . lsp)
   :init
   (add-to-list 'exec-path "~/.emacs.d/elixir-ls"))
   #+end_src
	 Fly check mode.
	 #+begin_src emacs-lisp
	 (use-package flycheck)
	 (global-flycheck-mode)
	 #+end_src
	 Configure =lsp-mode=
	 #+begin_src emacs-lisp
	 (use-package lsp-ui :commands lsp-ui-mode)
	 (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
	 #+end_src
** Ivy - Swiper
	 #+begin_src emacs-lisp
	 (use-package swiper)
	 (use-package ivy)
	 (ivy-mode 1)
	 (setq ivy-use-virtual-buffers t)
	 (setq enable-recursive-minibuffers t)
	 ;; enable this if you want `swiper' to use it
	 (setq search-default-mode #'char-fold-to-regexp)
	 (global-set-key "\C-s" 'swiper)
	 #+end_src
** Snippets
Use yasnippets and the snippets from github.com/hrs/dotfiles
#+begin_src emacs-lisp
(use-package yasnippet)
(setq yas-snippet-dirs '("~/.emacs.d/snippets/text-mode"))
(yas-global-mode 1)
(setq yas-indent-line 'auto)
(define-key yas-minor-mode-map (kbd "<tab>") 'yas-expand)
(define-key yas-minor-mode-map (kbd "TAB") 'yas-expand)
(define-key yas-minor-mode-map (kbd "<C-tab>") 'yas-expand)
#+end_src
** Management
   Projectile for project management.
   #+begin_src emacs-lisp
	 (use-package projectile)
   (projectile-mode +1)
   (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
   #+end_src
** Ido
	 Global enable IDO mode
	 #+begin_src emacs-lisp
	 (setq ido-enable-flex-matching t)
	 (setq ido-everywhere t)
	 (ido-mode 1)
	 (setq ido-use-filename-at-point 'guess)
	 (setq ido-create-new-buffer 'always)
	 (setq ido-file-extensions-order '(".ex" ".exs" ".org" ".md" ".txt" ".py" ".emacs" ".xml" ".el" ".ini" ".cfg" ".cnf"))
	 #+end_src
*** Smex
		Ido for Mx
		#+begin_src emacs-lisp
		(use-package smex)
		(smex-initialize)

		(global-set-key (kbd "M-x") 'smex)
		(global-set-key (kbd "M-X") 'smex-major-mode-commands)
		(global-set-key (kbd "C-c C-x m") 'execute-extended-command)
		#+end_src
** Magit
	 Magit keybinds.
	 #+begin_src emacs-lisp
	 (use-package magit)
	 (global-set-key (kbd "C-x g") 'magit-status)
	 (global-set-key (kbd "C-x p") 'magit-init)
	 #+end_src
** Spell check
   Enable spellcheck for both English and German in all =org-mode= and
   =text-mode= buffers.
dis   #+begin_src emacs-lisp
   (setq ispell-program-name "hunspell")
   (setq ispell-hunspell-dict-paths-alist
   '(("en_US" "~/.emacs.d/dict/en_US.aff")))
   (setq ispell-local-dictionary "en_US")
   (setq ispell-local-dictionary-alist
   ;; Please note the list `("-d" "en_US")` contains ACTUAL parameters passed to hunspell
   ;; You could use `("-d" "en_US,en_US-med")` to check with multiple dictionaries
   '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "en_US") nil utf-8)))
   ;; the following line won't make flyspell-mode enabled by default as you might think
   (flyspell-mode 1)
   (global-set-key (kbd "C-.") 'ispell-word)
   (add-hook 'text-mode-hook 'flyspell-mode)
   (add-hook 'org-mode-hook 'flyspell-mode)
   #+end_src
   German
   #+begin_src emacs-lisp
   (setq ispell-program-name "hunspell")
   (setq ispell-hunspell-dict-paths-alist
   '(("de_DE" "~/.emacs.d/dict/de_DE.aff")))
   (setq ispell-local-dictionary "de_DE")
   (setq ispell-local-dictionary-alist
   ;; Please note the list `("-d" "en_US")` contains ACTUAL parameters passed to hunspell
   ;; You could use `("-d" "en_US,en_US-med")` to check with multiple dictionaries
   '(("de_DE" "[[:alpha:]]" "[^[:alpha:]]" "[']" nil ("-d" "de_DE") nil utf-8)))
   ;; the following line won't make flyspell-mode enabled by default as you might think
   (flyspell-mode 1)
   (global-set-key (kbd "C-.") 'ispell-word)
   (add-hook 'text-mode-hook 'flyspell-mode)
   (add-hook 'org-mode-hook 'flyspell-mode)
   #+end_src
** Undo tree
	 Visual undo tree
	 #+begin_src emacs-lisp
	 (use-package undo-tree
  :defer t
  :diminish undo-tree-mode
  :init (global-undo-tree-mode)
  :custom
  (undo-tree-visualizer-diff t)
  (undo-tree-visualizer-timestamps t))
	#+end_src
* Programming
** Elixir
   Elixir major mode with syntax highlighting etc.
   #+begin_src emacs-lisp
   (unless (package-installed-p 'elixir-mode)
   (package-install 'elixir-mode))
  #+end_src
  Commands:\\
  Use
  -  M-x elixir-format
  to format the document following mix styleguide.
** Web mode
   Web mode and enable rainbow mode for hex colors.
   #+begin_src emacs-lisp
   (use-package web-mode)
   (add-hook 'web-mode-hook
   (lambda ()
   (rainbow-mode)
   (rspec-mode)
   (setq web-mode-markup-indent-offset 2)))
   #+end_src
** Golang
   Golang major mode.
   #+begin_src emacs-lisp
   (use-package go-mode)
   (use-package go-errcheck)
   #+end_src
** JavaScript
   JavaScript major mode.
   #+begin_src emacs-lisp
   (use-package coffee-mode)
   #+end_src
** Rust
   Rust major mode.
   #+begin_src emacs-lisp
   (use-package rust-mode)
   #+end_src
** Scala
   Scala major mode.
   #+begin_src emacs-lisp
   (use-package scala-mode
   :interpreter
   ("scala" . scala-mode))
   (use-package sbt-mode)
   #+end_src
** Markdown
	 Github markdown.
	 #+begin_src emacs-lisp
   (use-package markdown-mode
   :commands gfm-mode
   :mode (("\\.md$" . gfm-mode))
   :config
   (setq markdown-command "pandoc --standalone --mathjax --from=markdown")
   (custom-set-faces
   '(markdown-code-face ((t nil)))))
   #+end_src
* Org-mode
** Bullets
   Use org-bullets whenever possible.
   #+begin_src emacs-lisp
   (use-package org-bullets
   :init
   (add-hook 'org-mode-hook 'org-bullets-mode))
   #+end_src
** Folded
   Instead of "..." show a downward pointing arrow at the end of title.
	 TODO Change symbol or something.
   #+begin_src emacs-lisp
   (setq org-ellipsis "➘")
   #+end_src
** Indent mode
   Globally enable =org-indent-mode=
   #+begin_src emacs-lisp
   (add-hook 'org-mode-hook 'org-indent-mode)
   #+end_src
** Code block
   Highlight the entire code block when editing.
   #+begin_src emacs-lisp
   (setq org-src-fontify-natively t)
    #+end_src
** Todos
	 (copied from hrs/config)
*** Location
		Org document storage location for archive and other documents.
		#+begin_src emacs-lisp
		(setq org-directory "~/private/documents")

		(defun org-file-path (filename)
		"Return the absolute address of an org file, given its relative name."
		(concat (file-name-as-directory org-directory) filename))

		(setq org-archive-location
        (concat (org-file-path "archive.org") "::* From %s"))
		#+end_src
*** Archive
	 Hitting =C-c C-x C-s= will mark a todo as done and move it to an appropriate
	 place in the archive.
   #+begin_src emacs-lisp
   (defun hrs/mark-done-and-archive ()
   "Mark the state of an org-mode item as DONE and archive it."
   (interactive)
   (org-todo 'done)
   (org-archive-subtree))
   ;; Shortcut to archive
   (define-key org-mode-map (kbd "C-c C-x C-s") 'hrs/mark-done-and-archive)
   #+end_src
*** Time
	Record the time that a todo was archived.
    #+begin_src emacs-lisp
    (setq org-log-done 'time)
    #+end_src
*** Check
	 Ensure that a task can't be marked as done if it contains unfinished subtasks
	 or checklist items. This is handy for organizing "blocking" tasks
	 hierarchically.
   #+begin_src emacs-lisp
   (setq org-enforce-todo-dependencies t)
   (setq org-enforce-todo-checkbox-dependencies t)
   #+end_src
*** Options
	 Add new states to the todo cycle to extend the basic TODO and DONE states that
	 org mode normally provides.
   #+begin_src emacs-lisp
	 (setq org-todo-keywords
   '((sequence "TODO" "PROGRESS" "BLOCKED" "|" "DONE" "PAL")))
   #+end_src
** Export
	 Allow export to markdown and beamer (for presentations).
   #+begin_src emacs-lisp
   ;; (use-package ox-md)
   ;; (use-package ox-beamer)
	 ;; Add odt
	 (eval-after-load "org" '(require 'ox-odt nil t))
   #+end_src
*** Code
		Allow =babel= to evaluate Emacs lisp, Ruby, dot, or Gnuplot code.
    #+begin_src emacs-lisp
		(use-package ob-go)
		(use-package ob-elixir)

		(use-package gnuplot)
		(org-babel-do-load-languages
		'org-babel-load-languages
		'((emacs-lisp . t)
		(ruby . t)
		(dot . t)
		(gnuplot . t)
		(python . t)
		(go . t)
		(sql . t)
		(elixir . t)
		))
    #+end_src
		Don't ask before evaluating code blocks.
    #+BEGIN_src emacs-lisp
		(setq org-confirm-babel-evaluate nil)
    #+end_src
*** HTML
		Disable footer.
    #+begin_src emacs-lisp
		(setq org-html-postamble nil)
    #+end_src
** Tex
*** Parse
		Parse file after loading it.
    #+begin_src emacs-lisp
		(setq TeX-parse-self t)
    #+end_src
*** PDF-Latex
    #+begin_src emacs-lisp
		(setq TeX-PDF-mode t)
    #+end_src
*** Math mode
    #+begin_src emacs-lisp
		(add-hook 'LaTeX-mode-hook
		(lambda ()
		(LaTeX-math-mode)
		(setq TeX-master t)))
    #+end_src
** Notes
	 Deft for taking quick notes and storing them in plain text.
	 #+begin_src emacs-lisp
	 (use-package deft)
     (setq deft-default-extension "org")
     (setq deft-extensions '("org"))
	 (setq deft-directory "~/private/documents/notes")
     (setq deft-recursive t)
	 (setq deft-text-mode 'org-mode)
	 (setq deft-use-filename-as-title t)

	 (define-key org-mode-map (kbd "C-c n") 'deft)
	 (define-key org-mode-map (kbd "M-c n") 'deft-find-file)
	 #+end_src
** Agenda
*** Super
=org-super-agenda=
#+begin_src emacs-lisp
  (use-package org-super-agenda
    ;; :load-path "~/projects/org-super-agenda/"
    :after org-agenda
    :config
    (org-super-agenda-mode)

    (setq org-super-agenda-header-separator "")

    (defun zp/org-super-agenda-update-face ()
      (let ((ul-color (internal-get-lisp-face-attribute
                       'font-lock-comment-face :foreground)))
        (set-face-attribute 'org-super-agenda-header nil
                            :slant 'italic
                            :underline `(:color ,ul-color))))

    (defun zp/org-super-agenda-item-in-agenda-groups-p (item groups)
      "Check if ITEM is in agenda GROUPS."
      (let ((marker (or (get-text-property 0 'org-marker item)
                        (get-text-property 0 'org-hd-marker item))))
        (org-with-point-at marker
          (apply #'zp/org-task-in-agenda-groups-p groups))))

    (defun zp/org-super-agenda-groups (header groups)
      "Create org-super-agenda section for GROUPS with HEADER."
      `(:name ,header
        :pred (lambda (item)
                (zp/org-super-agenda-item-in-agenda-groups-p item ',groups))))

    (defun zp/org-super-agenda-groups-all ()
      `(,(zp/org-super-agenda-groups "Inbox" '("inbox"))
        ,(zp/org-super-agenda-groups "Life" '("life"))
        ,(zp/org-super-agenda-groups "Maintenance" '("mx"))
        ,(zp/org-super-agenda-groups "Professional" '("pro"))
        ,(zp/org-super-agenda-groups "Research" '("research"))
        ,(zp/org-super-agenda-groups "Activism" '("act"))
        ,(zp/org-super-agenda-groups "Hacking" '("hack"))
        ,(zp/org-super-agenda-groups "Curiosities" '("curios"))
        ,(zp/org-super-agenda-groups "Media" '("media"))))

    (defun zp/org-super-agenda-subtask-p (item)
      (let ((marker (or (get-text-property 0 'org-marker item)
                        (get-text-property 0 'org-hd-marker item))))
        (org-with-point-at marker
          (zp/is-subtask-p))))

    (defun zp/org-super-agenda-scheduled ()
      '((:name "Overdue"
         :face (:foreground "red")
         :scheduled past)
        (:name "Waiting"
         :and (:tag "waiting"
               :scheduled nil)
         :and (:tag "waiting"
               :scheduled today))
        (:name "Scheduled"
         :scheduled today)
        (:name "Subtasks"
         :and (:scheduled nil
               :pred (lambda (item)
                       (when zp/org-agenda-split-subtasks
                         (zp/org-super-agenda-subtask-p item)))))
        (:name "Current"
         :and (:not (:scheduled t)
               :not (:tag "waiting")))
        (:name "Later"
         :anything)))

    (defun zp/org-super-agenda-group-heads (item)
      (let ((marker (or (get-text-property 0 'org-marker item)
                        (get-text-property 0 'org-hd-marker item))))
        (org-entry-get marker "AGENDA_GROUP" nil)))

    (defun zp/org-super-agenda-stuck-project-p (item)
      (let ((marker (or (get-text-property 0 'org-marker item)
                        (get-text-property 0 'org-hd-marker item))))
        (org-with-point-at marker
          (zp/is-stuck-project-p))))

    (defun zp/org-super-agenda-finished-project-p (item)
      (let ((marker (or (get-text-property 0 'org-marker item)
                        (get-text-property 0 'org-hd-marker item))))
        (org-with-point-at marker
          (when (zp/is-confused-project-p)
            (zp/org-resolve-confused-project))
          (zp/is-finished-project-p))))

    (defun zp/org-super-agenda-projects ()
      '((:name "Group heads"
         :pred (lambda (item)
                 (zp/org-super-agenda-group-heads item)))
        (:name "Finished"
         :face (:foreground "purple")
         :pred (lambda (item)
                 (zp/org-super-agenda-finished-project-p item)))
        (:name "Stuck"
         :face (:foreground "red")
         :pred (lambda (item)
                 (zp/org-super-agenda-stuck-project-p item)))
        (:name "Waiting"
         :tag "waiting")
        (:name "Current"
         :anything))))
#+end_src
*** Gcal
	 Adding gcal for google calendar sync.
	 #+begin_src emacs-lisp
	 (use-package org-gcal)
	 ;; GCAL

	 (load-file "~/.emacs.d/secret.el")
	 (secret/init)

     #+end_src
*** Calendar
    #+begin_src emacs-lisp
     (defun todo/done ()
     (interactive)
     (org-todo 'done))

	 (define-key org-mode-map (kbd "C-c a") 'org-agenda)
	 (define-key org-mode-map (kbd "C-c d") 'org-deadline)
	 (define-key org-mode-map (kbd "C-c t") 'org-todo)
     (define-key org-mode-map (kbd "C-c s") 'org-schedule)
	 (define-key org-mode-map (kbd "C-c g") 'org-gcal-post-at-point)
	 (define-key org-mode-map (kbd "C-c f") 'org-gcal-fetch)
	 (define-key org-mode-map (kbd "C-c x") 'todo/done)
	 #+end_src
*** Path
    Use the entire home directory for agenda files.
    #+begin_src emacs-lisp
    (setq org-agenda-files '("~/private/documents/main.org"
    "~/private/documents/personal/personal.org"))
    #+end_src
    Add file to the list of included agenda files, bound =C-c v=
    #+begin_src emacs-lisp
	(define-key org-mode-map (kbd "C-c v") 'org-agenda-file-to-front)
    #+end_src
* Entertainment
** Games
   Malyon: Text adventure interface, games located under =/games=
   #+begin_src emacs-lisp
   (use-package malyon)
   #+end_src
