;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! helm-swoop)
(package! lsp-mode)
(package! lsp-ui)
(package! lsp-ivy)
(package! company-box)
(package! company-lsp)
(package! subword)
(package! org-superstar)
(package! malyon)
(package! org-roam)
(package! org-roam-server)
(package! ox-gfm)
(package! ox-ref)
(package! ox-odt)
(package! ob-go)
(package! ob-elixir)
(package! gnuplot)
(package! zen-mode)
